import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner"
import TaskReminderListener from "./components/tasks/askReminderListener";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background text-text-primary`}
      >
        <Providers>
          {children}
        </Providers>
        <Toaster
          position="bottom-left"
          richColors
          toastOptions={{
            style: {
              borderRadius: "12px",
            },
          }}
        />
        <TaskReminderListener />
      </body>
    </html>
  );
}
